# Generated by Django 3.1.1 on 2020-09-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20200912_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='to_pay',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
