# Generated by Django 3.1.1 on 2020-09-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='vat_bill_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
