# Generated by Django 3.1.1 on 2020-09-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_vat_bill_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='vat_bill_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
