# Generated by Django 3.1.1 on 2020-09-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='mm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
