# Generated by Django 3.1.1 on 2020-10-03 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_openingbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.term'),
        ),
        migrations.AlterUniqueTogether(
            name='openingbalance',
            unique_together={('customer', 'term')},
        ),
        migrations.RemoveField(
            model_name='openingbalance',
            name='date',
        ),
    ]
