# Generated by Django 3.1.1 on 2020-10-03 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_auto_20201003_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingbalance',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.term'),
        ),
    ]
