# Generated by Django 3.1.2 on 2020-10-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_auto_20201004_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_vat',
            field=models.BooleanField(default=False),
        ),
    ]
