# Generated by Django 3.1.2 on 2020-10-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_invoice_is_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='vat_bill_no',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Bill No'),
        ),
    ]
