# Generated by Django 3.1.2 on 2020-10-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_auto_20201004_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='density',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
