# Generated by Django 3.1.2 on 2020-12-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_auto_20201005_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.IntegerField(choices=[(1, 'Cheque'), (2, 'Cash'), (3, 'Bank Transfer'), (4, 'Internet Payment'), (5, 'Transport'), (6, 'Bank Deposit'), (7, 'Goods Returned')]),
        ),
    ]
