# Generated by Django 3.1.2 on 2021-03-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_auto_20201211_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='nepali_date',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
