# Generated by Django 3.1.2 on 2021-07-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_payment_nepali_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingbalance',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Opening Balance'),
        ),
    ]
