# Generated by Django 3.1.2 on 2021-07-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0017_auto_20210703_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingbalance',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Opening Balance'),
            preserve_default=False,
        ),
    ]
