# Generated by Django 3.1.2 on 2021-07-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0018_auto_20210703_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersystem',
            name='default_term',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=0),
        ),
    ]
