# Generated by Django 3.1.2 on 2021-08-16 07:45

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0020_auto_20210730_1050'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='term',
            constraint=models.CheckConstraint(check=models.Q(end_date__gt=django.db.models.expressions.F('start_date')), name='check_start_date'),
        ),
    ]
