# Generated by Django 3.1.2 on 2022-07-23 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0023_usersystem_billing_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersystem',
            name='billing_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.term'),
        ),
    ]
