# Generated by Django 3.1.2 on 2022-07-23 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0024_auto_20220723_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invnum',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice'),
        ),
    ]
